# -*- coding: utf-8 -*-
"""numero random grafica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNz_DNebITH75Y4GFWM5N7lV_ob21l5M
"""

import pandas as pd
import csv
import random
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

nombre_archivo = 'numeros_rand.csv'

df_vacio = pd.DataFrame()

df_vacio.to_csv(nombre_archivo, index=False)

datos = {
      'time': ['time'],
      'numero': ['numero']
}
df = pd.DataFrame(datos)
df.tail(1).to_csv(nombre_archivo, mode='a', index=False, header=False)

for i in range(100):
  numero = random.randint(1,100)
  time = datetime.datetime.now()
  datos = {
      'time': [time.microsecond],
      'numero': [numero]
  }
  df = pd.DataFrame(datos)
  df.tail(1).to_csv(nombre_archivo, mode='a', index=False, header=False)

df_leido = pd.read_csv(nombre_archivo)
df_leido.columns

df_leido['time'] = pd.to_datetime(df_leido['time'])

plt.figure(figsize=(10, 6))
plt.plot(df_leido['time'], df_leido['numero'], marker='o', linestyle='-')

plt.title('Valores de Número a lo largo del Tiempo')
plt.xlabel('Hora')
plt.ylabel('Número Generado')
plt.grid(True)

plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

